language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install flake8"
  - "pip install flake8-assertive pep8-naming"
  - "pip install -r requirements.txt"
script:
  - "flake8 ."
  - "python -m unittest"
